<a href="https://colab.research.google.com/github/Quratulain786/-R-versus-Python-EDA/blob/main/loss_or_cost_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])


<h3 style='color:blue'>Implement Mean Absolute Error</h3>

In [ ]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae


In [ ]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

**Implement same thing using numpy in much easier way**

In [ ]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [ ]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [ ]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [ ]:
mae_np(y_predicted, y_true)

0.5

<h3 style='color:blue'>Implement Log Loss or Binary Cross Entropy</h3>

In [ ]:
np.log([0])

C:\Users\Window\AppData\Local\Temp\ipykernel_19040\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [ ]:
epsilon = 1e-15

In [ ]:
np.log([1e-15])

array([-34.53877639])

In [ ]:
y_predicted

array([1, 1, 0, 0, 1])

In [ ]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [ ]:
1-epsilon

0.999999999999999

In [ ]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [ ]:
y_predicted_new = np.array(y_predicted_new)

In [ ]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [ ]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [ ]:
log_loss(y_true, y_predicted)

17.2696280766844

<h3 style='color:purple'>Exercise</h3>

Implement mean squared error (or MSE) in two ways,

1) Without using numpy (i.e. using plain python)

2) With the use of numpy

# **Without using numpy (i.e. using plain python)**

In [ ]:
 def mse(y_predicted, y_true):
       total_error = 0
       for yp, yt in zip(y_predicted, y_true):
        total_error += (yp - yt)**2
        print("Total error is:",total_error)
        mse = total_error/len(y_predicted)
        print("Mean Squared error is:",mse)
        return mse

In [ ]:
y_predicted = np.array([11,11,10,10,11])
y_true = np.array([20.30,0.27,11,10,10.5])

mse(y_predicted, y_true)

Total error is: 86.49000000000001
Mean Squared error is: 17.298000000000002


17.298000000000002

# **2) With the use of numpy**

In [ ]:
# use mean() and square() methods
from sklearn.metrics import mean_squared_error
# use mean_squared_error() function
mse = mean_squared_error(y_true, y_pred)

# print result
print("MSE:", mse)

In [ ]:
mse

40.574580000000005

In [ ]:
# import necessary libraries
import pandas as pd
from sklearn.metrics import mean_squared_error



# use mean_squared_error() function
mse = mean_squared_error(y_predicted, y_true)

# print result
print("MSE:", mse)

MSE: 40.574580000000005


In [ ]:
# using panda's mean()
mse = ((y_predicted- y_true) ** 2).mean()

# print result
print("MSE:", mse)

MSE: 40.574580000000005
